### ISSUE TITLE
python tkinter 累加累減程式

### ISSUE THREAD

**Issue by Lin0904** [charlax/professional-programming#23]
def add():
    for i in range(1,101):
        sum+=i
        result1.set('累加結果為:'+sum)
def sub():
    for i in range(100,0,-1):
        sum-=i
        result1.set('累減結果為:'+sum)
import tkinter
result1=tkinter.StringVar()
win=tkinter.Tk()
win.title('累加累減程式')
win.geometry('500x500')
label=tkinter.Label(win,text='累加累減程式',fg='red')
label.pack()
frame1=tkinter.Frame(win)
frame1.pack()
button1=tkinter.Button(frame1,text='+',command=add)
button1.grid(row=0,column=0)
button2=tkinter.Button(frame1,text='-',command=sub)
button2.grid(row=0,column=1)
result=tkinter.Label(win,textvariable=result1,fg='red')
result.pack()
win.mainloop()
 

結果發生錯誤:
Traceback (most recent call last):

  File "<ipython-input-44-5f1c7fab25ae>", line 1, in <module>
    runfile('C:/Users/user/Desktop/加減程式.py', wdir='C:/Users/user/Desktop')

  File "C:\Users\user\Anaconda3\envs\py35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\user\Anaconda3\envs\py35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/user/Desktop/加減程式.py", line 10, in <module>
    result1=tkinter.StringVar()

  File "C:\Users\user\Anaconda3\envs\py35\lib\tkinter\__init__.py", line 334, in __init__
    Variable.__init__(self, master, value, name)

  File "C:\Users\user\Anaconda3\envs\py35\lib\tkinter\__init__.py", line 233, in __init__
    self._root = master._root()

AttributeError: 'NoneType' object has no attribute '_root'

**Comment by charlax** [comment]
You must be posting on the wrong repo...

**Comment by Lin0904** [comment]
What do you mean?

**Comment by JamieCorkhill** [comment]
He means that this is a repository that provides Full Stack resources having to do with professional programming. Your Python issue is non-relevant and has nothing to do with this repo. You must be posting in the wrong place.
________________________________

**Comment by Lin0904** [comment]
ok

**Comment by creatorot** [comment]
Почему ты ему помогаешь  я устал помоги мне все почты отжали у меня нет свободы и я ничего не могу сделать31 янв. 2019 г. 16:01 пользователь Lin0904 <notifications@github.com> написал:def add():

for i in range(1,101):

sum+=i

result1.set('累加結果為:'+sum)

def sub():

for i in range(100,0,-1):

sum-=i

result1.set('累減結果為:'+sum)

import tkinter

result1=tkinter.StringVar()

win=tkinter.Tk()

win.title('累加累減程式')

win.geometry('500x500')

label=tkinter.Label(win,text='累加累減程式',fg='red')

label.pack()

frame1=tkinter.Frame(win)

frame1.pack()

button1=tkinter.Button(frame1,text='+',command=add)

button1.grid(row=0,column=0)

button2=tkinter.Button(frame1,text='-',command=sub)

button2.grid(row=0,column=1)

result=tkinter.Label(win,textvariable=result1,fg='red')

result.pack()

win.mainloop()

結果發生錯誤:

Traceback (most recent call last):

File "", line 1, in 

runfile('C:/Users/user/Desktop/加減程式.py', wdir='C:/Users/user/Desktop')

File "C:\Users\user\Anaconda3\envs\py35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile

execfile(filename, namespace)

File "C:\Users\user\Anaconda3\envs\py35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile

exec(compile(f.read(), filename, 'exec'), namespace)

File "C:/Users/user/Desktop/加減程式.py", line 10, in 

result1=tkinter.StringVar()

File "C:\Users\user\Anaconda3\envs\py35\lib\tkinter_init_.py", line 334, in init

Variable.init(self, master, value, name)

File "C:\Users\user\Anaconda3\envs\py35\lib\tkinter_init_.py", line 233, in init

self._root = master._root()

AttributeError: 'NoneType' object has no attribute '_root'

**Comment by creatorot** [comment]
Я в программировании не селен а тут в домен мой же меня запихали и кредитов уйму набрали 31 янв. 2019 г. 16:01 пользователь Lin0904 <notifications@github.com> написал:def add():

for i in range(1,101):

sum+=i

result1.set('累加結果為:'+sum)

def sub():

for i in range(100,0,-1):

sum-=i

result1.set('累減結果為:'+sum)

import tkinter

result1=tkinter.StringVar()

win=tkinter.Tk()

win.title('累加累減程式')

win.geometry('500x500')

label=tkinter.Label(win,text='累加累減程式',fg='red')

label.pack()

frame1=tkinter.Frame(win)

frame1.pack()

button1=tkinter.Button(frame1,text='+',command=add)

button1.grid(row=0,column=0)

button2=tkinter.Button(frame1,text='-',command=sub)

button2.grid(row=0,column=1)

result=tkinter.Label(win,textvariable=result1,fg='red')

result.pack()

win.mainloop()

結果發生錯誤:

Traceback (most recent call last):

File "", line 1, in 

runfile('C:/Users/user/Desktop/加減程式.py', wdir='C:/Users/user/Desktop')

File "C:\Users\user\Anaconda3\envs\py35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile

execfile(filename, namespace)

File "C:\Users\user\Anaconda3\envs\py35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile

exec(compile(f.read(), filename, 'exec'), namespace)

File "C:/Users/user/Desktop/加減程式.py", line 10, in 

result1=tkinter.StringVar()

File "C:\Users\user\Anaconda3\envs\py35\lib\tkinter_init_.py", line 334, in init

Variable.init(self, master, value, name)

File "C:\Users\user\Anaconda3\envs\py35\lib\tkinter_init_.py", line 233, in init

self._root = master._root()

AttributeError: 'NoneType' object has no attribute '_root'
